config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # This defines a route rule that says when we receive
  # a GET request with the URL '/', handle it with the
  # WelcomeController with the index action inside that
  # controller.
  get('/', {to: 'welcome#index', as: 'root'})

  get '/contacts/new', {to: 'contacts#new' }
  post '/contacts', {to: 'contacts#create'}

  resources :users, only: [:new, :create]

  # `resource` is singular instead of `resources`
  # Unlike `resources`, `resource` will create routes that
  # do CRUD operation on only one thing. There will be no
  # index routes, and no route will have an `:id`
  # wild card. When using a singular resource,
  # the controller must still be plural. 
  resource :session, only: [:new, :create, :destroy]

  # # question new page
  # # when someone requests /questions/new it will be handled by the NEW method
  # # inside of questions controller
  # get '/questions/new', {to: 'questions#new', as: :new_question}
  # # get '/questions/:id', {to: 'questions#show', as: :question }
  #
  # # handles submission of new questions form
  # post 'questions', {to: 'questions#create', as: :questions}
  #
  # # question show page
  # # adding the alias `as: :question` will create the helper paths/url to question_path
  # # we can use these like so: question_path(<id>), question_url(<id>)
  # get '/questions/:id', {to: 'questions#show', as: :question}
  #
  # # question index page
  # get '/questions', {to: 'questions#index'}
  #
  # # question edit page
  # get '/questions/:id', {to: 'questions#edit', as: :edit_question}
  #
  # # handles submission of form on the question edit page
  # patch '/questions/:id', {to: 'questions#update'}
  #
  # delete '/questions/:id', {to: 'questions#destroy'}

  # this builds all of the above routes for us ;)
  # 'resources' method will generate all CRUD routes
  # following RESTful conventions for a resource
  # It will assume there is a controller named after the
  # first argument, pluralized and PascalCased
  resources :questions do
    # Routes written inside of a block passed to
    # a resources method will be pre-fixed by
    # a path corresponding to the passed in symbol.
    # In this case, all nested routes will be pre-fixed
    # with '/questions/:question_id'
    resources :answers, only: [:create, :destroy]
    # equivalent to:
    # resources :answers, except: [:show, :index, :new, :edit, :update]
    # question_answers_path(<question-id>),
    # question_answer_url(<question-id>)
    # question_answers_path(@question.id)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  # This is the Question model. We generated this
  # file with the command:
  # rails g model question title:string body:text
  # This command also generates a migration file
  # in db/migrate

  # Rails will add attr_accessors for all columns
  # of the table (i.e. title, body, created_at, updated_at)

  # Adding 'dependent: :destroy' option tells Rails to
  # delete associated records before deleting the record
  # itself. In this case, when a question is deleted
  # its answers are deleted first to satisfy the foreign
  # key constraint.
  # You can also use 'dependent: :nullify' which will
  # cause all associated answers to have their question_id
  # column set to NULL before the question is destroyed.

  # If you don't use either dependent option, you can end
  # up with answers in your db referencing question_ids
  # that no longer exist, likely leading to errors.
  # Always set a dependent option to help maintain
  # referential integrity.
  belongs_to :user
  has_many(:answers, dependent: :destroy)
  # has_many(:answers, dependent: :destroy) adds
  # the following instance methods to the Question model:

  # .answers
  # .answers<<(object, ...)
  # .answers.delete(object, ...)
  # .answers.destroy(object, ...)
  # .answers=(objects)
  # .answers_singular_ids
  # .answers_singular_ids=(ids)
  # .answers.clear
  # .answers.empty?
  # .answers.size
  # .answers.find(...)
  # .answers.where(...)
  # .answers.exists?(...)
  # .answers.build(attributes = {}, ...)
  # .answers.create(attributes = {})
  # .answers.create!(attributes = {})
  # .answers.reload

  # Create validations by using the 'validates' method
  # The arguments are (in order):
  # - A column name as a symbol
  # - Named arguments, corresponding to the validation
  # rules

  # To read more on validations, go to:
  # https://guides.rubyonrails.org/active_record_validations.html

  validates(:title, presence: true, uniqueness: true)

  validates(
    :body,
    presence: {message: "must exist"},
    length: { minimum: 10 }
  )

  validates(
    :view_count,
    numericality: {greater_than_or_equal_to: 0, allow_blank: true}
  )

  # Custom validation
  # The method for custom validations is singular
  # unlike the 'validates' method for regular validations
  validate :no_monkey

  # before_validation is a lifecycle callback
  # method that allows to respond to events during
  # the life of a model instance (i.e. being validated,
  # being created, being updated etc.)
  # All lifecycle callback methods take a symbol
  # named after a method and calls that method
  # at the appropriate time.
  before_validation(:set_default_view_count)

  #  For all available methods go to:
  # https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks
  def cool_view_count
    view_count
  end

  # Create a scope with a class method
  # https://edgeguides.rubyonrails.org/active_record_querying.html#scopes

  # def self.recent
  #   order(created_at: :desc).limit(10)
  # end

  # Scopes are such a commonly used feature, that
  # there's another way to create them quicker. It
  # takes a name and a lambda as a callback
  scope(:recent, -> { order(created_at: :desc).limit(10) })


  # def self.search(query)
  #   where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%")
  # end
  # Equivalent to:
  scope(:search, -> (query) { where("title ILIKE ? OR body ILIKE ?", "%#{query}%", "%#{query}%") })

  private

  def no_monkey
    # &. is the safe navigation operator. It's used
    # like the . operator to call methods on an object.
    # If the method doesn't exist for the object, 'nil'
    # will be returned instead of getting an error
    if body&.downcase&.include?("monkey")
      # To make a record invalid. You must add a
      # validation error using the 'errors' 'add' method
      # It's arguments (in order):
      # - A symbol for the invalid column
      # - A error message as a string
      self.errors.add(:body, "must not have monkeys")
    end
  end

  def set_default_view_count
    # If you are a writing to an attribute accessor, you
    # must prefix with 'self.' Which you don't need to do
    # if you are reading it instead.
    self.view_count ||= 0
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit,:update,:destroy]
  
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    # # The 'params' object available in controllers
    # # is composed of the query string, url params,
    # # and the body of a form
    # # (e.g. req.query + req.params + req.body)
    #
    # # A good trick to see if your routes are working
    # # and you're getting the data that you want, is to
    # # render the params as JSON. This is like doing
    # # res.send(req.body) in Express

    # Use 'require' on the params object to retrieve
    # the nested hash of a key usually corresponding to
    # the name-value pairs of a form

    # Then use permit to specify all input names that
    # are allowable (as symbols).
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      flash[:notice] = "Question created successfully"
      # if question is saved successfully redirect to question show page
      redirect_to question_path(@question)
    else
      # render views/questions/new.html.erb
      render :new
    end
  end

  def show
    # For the 'form_with' helper
    @answer = Answer.new
    # For the list of answers
    @answers = @question.answers.order(created_at: :desc)
  end

  def edit
  end

  def update
    # attempt to edit the existing question with new values
    if @question.update question_params
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "Question destoryed!"
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    # params.require(:question): We must have a question object on the params of this request
    # .permit(:title, :body): for security reasons we need to only permit the title and body keys/attributes of the question
    params.require(:question).permit(:title, :body)
  end

  def find_question
    # get the current value inside of the db
    @question = Question.find params[:id]
  end

  def authorize! 
    redirect_to root_path, alert: "Not Authorized!" unless 
    can?(:crud, @question)
  end 

end

app/views/questions/_form.html.erb
<%#
  To create a form for a resource (i.e. a model), use
  the form_wth helper instead of formm_tag. Its usual
  arguments are:
  - A named argument 'model' which is assigned an
  instance of a model (i.e. a new question)
  - A named argument 'local', which will prevent
  the form from submitting its data using AJAX.
  - A block that is passed the form object, where
   we build the HTML inside the form (i.e. labels,
   inputs, submission buttons, etc.)
    All data from the input fields a form built with this will have its name-value nested in a hash named
   after the class of the passed in model
   (e.g. <input type="text" name="question[title]" id="question_title"> => { "question": { "title": "What?"} })
%>
<%= render '/shared/signuperrors', obj: @question%>

<div class="container-fluid offset-2">
<div class="form-group row ">
    <div class="col-sm-10">
        <%= form_for(@question, :html => {class:'form-horizontal', role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title%>
            </div>
            <div class="col-sm-10">
                <%= f.text_field :title, class: "form-control", placeholder: "Name of question", autofocus: true %>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :body%>
            </div>
            <div class="col-sm-10">
                <%= f.text_area :body,rows:10,class: "form-control", placeholder: "Description", autofocus: true %>
            </div>
        </div>
        

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-2">
                <%= f.submit class: 'btn btn-primary btn-lg' %>
            </div>
        </div>

        <%end%>

    </div>
</div>
</div>
<div class="col-4 offset-4">
    [ <%= link_to  "Cancel create and return to question listing", questions_path %> ]
    </div>

app/views/questions/edit.html.erb
<h1>Question Edit Page</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1 class="question-index" align="center">All Questions</h1>

<% @questions.each do |question| %>
<div class="row">
    <div class="col-sm-10 offset-1">
        <div class="card card-body bg-light">
            <div class="question-title">
                <%= link_to question.title, question_path(question)%>
            </div>
            <div class="question-body">
                <%= question.body%>
            </div>
<!--           
    <div class="question-actions">
        <%= link_to  "Edit this question", edit_question_path(question), class: "btn btn-sm btn-primary" %>
        <%= link_to 'Delete this listing', question_path(question), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-sm btn-danger ml-1"%>
    </div> -->
</div>
</div>
</div>
<%end%>

app/views/questions/new.html.erb
<br>  
<h1 align="center">Make a new Question</h1>
<%= render 'form'%>

app/views/questions/show.html.erb
<%#
To create a form for a resource (i.e. a model), use the form_with
helper instead of the form_tag. Its usual arguments are:
- A named arg. model which is assigned an instance of a model
(e.g. a new question)
- A named arg. local which will prevent the form from submitting
its data using AJAX.
- A block that is passed the form object wherein we build
the HTML inside the form (e.g. labels, inputs, submission buttons, etc)
All data from the input fields a form built with this will have its
name-value nested in a hash named after the class of the passed in model.
(e.g. <input name="question[title]"> => { "question": { "title": "What?" } })
%>


<h2 align="center">Title: <%= @question.title%></h2>
<div align="center">
  <h4 class="body"><strong>Body:
    </strong></h4>
  <%= simple_format(@question.body)%>

  <h5 class="created-at"><strong>
    </strong><%=@question.created_at%></h5>
    <hr>
  <div class="question-actions row">

    <%if can? :crud, @question%> 
    <%= link_to  "Edit this question", edit_question_path(@question), class: "btn btn-xs btn-primary" %>
    <%= link_to  "View all questions", questions_path, class: "btn btn-xs btn-success ml-2" %>
    <%= link_to 'Delete this listing', question_path(@question), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-xs btn-danger ml-2"%>
  <%end%>

  </div>
</div>
<br>

<%= form_with(model: [@question, @answer], local: true) do |f| %>
<% if @answer.errors.any? %>
<ul>
  <% @answer.errors.full_messages.each do |msg|%>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.text_area :body,rows:5,class: "form-control", placeholder: "Add a comment!", autofocus: true %>
  </div>

  <div class="col-sm-2">
    <%= f.text_field :rating, class: "form-control mt-3", placeholder: "Rate 1-5", autofocus: true %>
  </div>
</div>

<div class="col-sm-offset-4">
  <%= f.submit class: 'btn btn-primary create-btn' %>
</div>
<% end %>


  <div class="row" align="center">
    <% @answers.each do |answer| %>
      <div class="col-sm-4">
          <div class="question-answer">
            <%= answer.body %>
          </div>
          <div class="col-sm-offset-4 col-sm-2">
            <%if can? :crud, answer %>
            <%= link_to("Delete",question_answer_path(@question, answer),method: :delete,data: {confirm: "Are you sure?"},class: 'btn btn-primary del-btn')%>
            <%end%>
          </div>
          <p class="question-answer"> Answered <%= time_ago_in_words(answer.created_at) %> ago </p>
        </div>
  <% end %>