config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # This defines a route rule that says when we receive
  # a GET request with the URL '/', handle it with the
  # WelcomeController with the index action inside that
  # controller.
  get('/', {to: 'welcome#index', as: 'root'})

  get '/contacts/new', {to: 'contacts#new' }
  post '/contacts', {to: 'contacts#create'}

  resources :users, only: [:new, :create]

  # `resource` is singular instead of `resources`
  # Unlike `resources`, `resource` will create routes that
  # do CRUD operation on only one thing. There will be no
  # index routes, and no route will have an `:id`
  # wild card. When using a singular resource,
  # the controller must still be plural. 
  resource :session, only: [:new, :create, :destroy]

  # # question new page
  # # when someone requests /questions/new it will be handled by the NEW method
  # # inside of questions controller
  # get '/questions/new', {to: 'questions#new', as: :new_question}
  # # get '/questions/:id', {to: 'questions#show', as: :question }
  #
  # # handles submission of new questions form
  # post 'questions', {to: 'questions#create', as: :questions}
  #
  # # question show page
  # # adding the alias `as: :question` will create the helper paths/url to question_path
  # # we can use these like so: question_path(<id>), question_url(<id>)
  # get '/questions/:id', {to: 'questions#show', as: :question}
  #
  # # question index page
  # get '/questions', {to: 'questions#index'}
  #
  # # question edit page
  # get '/questions/:id', {to: 'questions#edit', as: :edit_question}
  #
  # # handles submission of form on the question edit page
  # patch '/questions/:id', {to: 'questions#update'}
  #
  # delete '/questions/:id', {to: 'questions#destroy'}

  # this builds all of the above routes for us ;)
  # 'resources' method will generate all CRUD routes
  # following RESTful conventions for a resource
  # It will assume there is a controller named after the
  # first argument, pluralized and PascalCased
  resources :questions do
    # Routes written inside of a block passed to
    # a resources method will be pre-fixed by
    # a path corresponding to the passed in symbol.
    # In this case, all nested routes will be pre-fixed
    # with '/questions/:question_id'
    resources :answers, only: [:create, :destroy]
    # equivalent to:
    # resources :answers, except: [:show, :index, :new, :edit, :update]
    # question_answers_path(<question-id>),
    # question_answer_url(<question-id>)
    # question_answers_path(@question.id)
  end
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="#">Awesome Answers</a>
            by <a href="https://github.com/agamaoaljan6">Aljan Agamao</a>
        </small>
        <nav>
            <ul>
                <li>        
                    <%=link_to 'Contact Us', contacts_path, class: 'nav-item nav-link'%>
                </li>

            </ul>
        </nav>
    </footer>
    </div>

app/views/layouts/_messages.html.erb
<div class="row">
        <div class="col-sm-10 offset-1">  <br>
          <% flash.each do |name,msg|%>
          <div class='alert alert-<%="#{name}"%>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
          <%end%>
        </div>
      </div>
      
      

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <%= link_to 'Awesome Answers', root_path, class:"navbar-brand", id:"logo" %>
  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%=link_to 'Questions', questions_path, class: 'nav-item nav-link'%>
  
  
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
  
            <%=link_to 'New Question', new_question_path, class: 'dropdown-item'%>
  
            <!-- <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a> -->
          </div>
        </li>
        <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
      </ul>
      <form class="form-inline my-2 my-lg-0">
  
        <% if user_signed_in? %>
        <%=link_to 'Sign Out', session_path,method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0 mr-2'%>
        <% else %>
        <%=link_to 'Sign Up', new_user_path, class: 'btn btn-info my-2 my-sm-0 mr-2'%>
        <%=link_to 'Sign In', new_session_path, class: 'btn btn-info my-2 my-sm-0 mr-2'%>
        <%end%>
  
      </form>
      
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswersMay2019</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>
      <div class="container">
    <%= yield %>
  </div>
  
    <%= render 'layouts/footer'%>
  </body>
</html>